name: status_check
on: 
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      # - name: checkout remote repo test
      #   uses: actions/checkout@v2
      #   with:
      #     fetch-depth: 0
      #     repository: ait-dmirian/public-test
      #       #path: './bar'
      - name: check_remote
        run: |
          echo "GH variables:"
          echo ${GITHUB_HEAD_REF}
          echo ${GITHUB_REF_NAME}
          echo ${GITHUB_REPOSITORY}
          echo ${GITHUB_REPOSITORY_OWNER} 
          echo "GITHUB_HEAD_REF = ${GITHUB_HEAD_REF}"
          curl -s "https://api.github.com/repos/ait-dmirian/public-test/pulls?base=main&state=all&head=ait-dmirian:${GITHUB_HEAD_REF}" > result.txt
          pr_name=$(grep "ait-dmirian:${GITHUB_HEAD_REF}" result.txt)
          echo "Echo: $pr_name"
          grep "state" result.txt
          if [ "$pr_name" ]; then echo "The PR name is: $pr_name"; else echo "There is no PR for ait-dmirian:${GITHUB_HEAD_REF}" && exit 1;  fi
