name: status_check
on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      # - name: checkout remote repo test
      #   uses: actions/checkout@v2
      #   with:
      #     fetch-depth: 0
      #     repository: ait-dmirian/public-test
      #       #path: './bar'
      - name: check_remote
        run: |
          # ls -la && pwd 
          # response=$(curl --write-out '%{http_code}' --silent --output /dev/null https://api.github.com/repos/ait-dmirian/public-test/pulls/2/merge)
          # echo $response
          # if [ "$response" != 204 ]; then exit 1; fi
          # #gh pr list
          #curl -s 'https://api.github.com/repos/ait-dmirian/public-test/pulls?base=main&state=any&head=ait-dmirian:ait-dmirian-patch-3' | grep "ait-dmirian:ait-dmirian-patch-3"
          #if [ "$?" != 0 ]; then exit 1; fi
          #echo ${GITHUB_REF_NAME}
          #echo ${GITHUB_REPOSITORY}
          #echo curl -s "https://api.github.com/repos/ait-dmirian/public-test/pulls?base=main&state=any&head=ait-dmirian:${GITHUB_REF_NAME}"
          # if grep won't find anything then resul=nothign will fail the job
          #result=$(curl -s "https://api.github.com/repos/ait-dmirian/public-test/pulls?base=main&state=all&head=ait-dmirian:${GITHUB_REF_NAME}" | grep "ait-dmirian:${GITHUB_REF_NAME}") 
          # If result is not empty echo it, otherwise exit with error and fail job 
          #[[ ! -z "$result" ]] && echo $result || exit 1           
          curl -s "https://api.github.com/repos/ait-dmirian/public-test/pulls?base=main&state=all&head=ait-dmirian:${GITHUB_REF_NAME}" > result.txt
          pr_name=$(grep "ait-dmirian:${GITHUB_REF_NAME}" result.txt)
          if [ "$pr_name" ]; then echo "$pr_name"; else echo "There is no PR for ait-dmirian:${GITHUB_REF_NAME}" && exit 1;  fi
