name: status_check
on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: check_remote
        run: |
          ll 
          response=$(curl --write-out '%{http_code}' --silent --output /dev/null https://api.github.com/repos/ait-dmirian/public-test/pulls/2/merge
          echo $response
          [ "$response" -eq 204 ]
          echo $?

#