name: status_check
on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      #- name: checkout code
      #  uses: actions/checkout@v2
      - name: check_remote
        run: |
          ls -la && pwd 
          response=$(curl --write-out '%{http_code}' --silent --output /dev/null https://api.github.com/repos/ait-dmirian/public-test/pulls/7/merge)
          echo $response
          if [ "$response" != 204 ]; then exit 1; fi

##